### PR TITLE
add xmldom@0.1.19 package into exclude list, as it was recently included in mock-pathfinder

### PR DESCRIPTION
**Pull request by lewisdaly**
The title says it all

### CODE REVIEW

**Review by rmothilal — APPROVED** [review]
Happy

**Comment by elnyry-sam-k** [comment]
As the text says "_Allows either MIT or LGPL License_", why can't we pick MIT, which is Apache 2.0 compatible?

**Comment by lewisdaly** [comment]
> As the text says "_Allows either MIT or LGPL License_", why can't we pick MIT, which is Apache 2.0 compatible?

Indeed we can, but the license scanner tool looks at the license entry in the `package.json`, which says LGPL in spite of the project allowing either choice. So by adding it to the whitelist, we eliminate a false positive for the license scanner.

**Comment by elnyry-sam-k** [comment]
Ok, please go ahead with this then.

**Pull request merged**
